[[ -s "$HOME/.profile" ]] && source "$HOME/.profile" # Load the default .profile

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

source ~/.dotfiles/shell/sys/path
source ~/.dotfiles/shell/sys/alias

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

source /usr/local/opt/autoenv/activate.sh
source /usr/local/bin/virtualenvwrapper.sh
